version: '3.8'

services:
  db:
    image: postgres:16.2
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    image: redis:6.0.20
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379" 
    env_file:
      - .env

  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/myapp
      - ./statics:/myapp/public/statics
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

volumes:
  postgres-data:
  redis-data:
