version: '3.8'

services:
  db:
    image: postgres:16.2
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    image: redis:6.0.20
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379" 
    env_file:
      - .env

  web:
    image: bustracker
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      DATABASE_HOST: db
      REDIS_URL: redis://redis:6379/1

  resque_worker:
    image: bustracker
    command: bundle exec env rake resque:workers QUEUE='*' COUNT='4'
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      DATABASE_HOST: db
      REDIS_URL: redis://redis:6379/1

volumes:
  postgres-data:
  redis-data:
